 # this is a yml file. working in yml file

# informatie desper comenzi: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

name: Build and Deploy code

on: [push, pull_request] # this trigger the workflow



# creating a job
jobs: 
    job1:
      # setup the environment variable/ if i insertiti here is only for the job 1, if i inserted abive the jobs - it will affetc all the jobs
        env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: password456
          DATABASE_NAME: FastAPI_Project
          DATABASE_USERNAME: postgres
          SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
           
        # specifying the os for the virtual machine to run the ci/cd
        runs-on: windows-2022
        # providibg the list of steps
        steps:
            #giving a name and a comand for every step/ toata informatia asta e si pe linkul mentionat mai sus/ sa verifi ce inseamna un job, un step si cum functioneaza
            - name: pulling git repo
            # teh actually comand that need to run in the machine to pull the commande above
              uses: actions/checkout@v2  # aceasta e din codul exemplu de pe github
#dupa ce am scris comenzile de sus ca sa commit toate am scris in terminal: 1.git add --all; 2.git commit -m "adding first github action"; 3.git push (origin main - e optional).
# dupa ce scris comenzile ontru pe repositoriul din github + Action + ai o sa imi apara primul action
# https://github.com/marketplace?ocid=AIDcmm153qff2f_SEM__k_d615bd7e8cc21d2061dadb3afa4709d0_k_  - am setat python de pe acest link 
            - name: install python version 3.11
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'
                # updating the pip
            - name: update pip
              run: python -m pip install --upgrade pip
              # install all the dependencie, and packages from requirements.txt
            - name: install all dependencies
              run: pip install -r requirements.txt
#dupa ce am scris comenzile de sus ca sa commit toate am scris in terminal: 1.git add --all; 2.git commit -m "adding first github action"; 3.git push
 # dupa verific iarasi github + Actions

 # run pytest
            - name: test with pytest
              run: 
                pip install pytest
                pytest

            - name: say hi to svetlana
              run: print "hello svetlana"
